title: Hi!
description: Our destiny is in the stars.
url: https://isrecalpear.com/
avatar: /avatar.jpeg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg
remote_theme: isrecalpear/not-pure-poole

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

social:
  name: Isrecal
  links:
    - https://github.com/isrecalpear
lang: zh_cn

sass:
  sass_dir: _sass
  style: :compressed

author:
  name: IsrecalPear
  url: https://github.com/isrecalpear/
